### PR TITLE
colorize bash/ksh/zsh profile setting files

### PR DESCRIPTION
**Pull request by ildar-shaimordanov**
colorize profile setting files in the same way as to regular shell scripts.
Supportable shells:
	bash/ksh/zsh
Supportable files:
	.bashrc
	.kshrc
	.zshrc
	.bash_profile
	.profile
	.zprofile

### CODE REVIEW

**Comment by AnrDaemon** [comment]
https://gist.github.com/AnrDaemon/083c1e028b66b80b4d717576dd9506c4
if you so need it.

**Comment by ildar-shaimordanov** [comment]
@AnrDaemon 
Thank you for your comment. I have reviewed and found that your solution is wider and narrower at the same time. 
-- it has impact on viewing more dot files
-- it is specific for bash only
-- it requires the separate hrc file and the separate menu item

It the most of cases there is no necessity to open history files. Anyway, some people prefer separate files for aliases, fucntions and other settings. 

Thank you for the hint. I will include absent things into my pull request.

**Comment by AnrDaemon** [comment]
I'm only using bash and dash. You may tweak the RE as you prefer.

**Comment by ildar-shaimordanov** [comment]
I've performed some tests trying to accept the zoo of all sh/ksh/zsh/bash dotfiles. Trying to take into account all possible cases for profile/shrc/login/logout leads to crash of the plugin. Let's fix the current suggestion for main cases of profile/shrc files. Other cases would be fixed later, in the following PRs.

**Pull request merged**
