### PR TITLE
Increase weight of fsharp filename to avoid conflicts with cpp (same …

### PR DESCRIPTION
**Pull request by nightroman**
…first line comments).

### CODE REVIEW

**Comment by techtonik** [comment]
How about writing tests for this?

**Comment by nightroman** [comment]
What kind of tests? I have some local semi-automatic tests for schemes that I develop and change. But this is a change in a proto file. I am not sure.

**Comment by techtonik** [comment]
Test that file selection mechanism is not borked.

**Comment by nightroman** [comment]
Honestly, I have no idea how to write such tests. It's not like I am against tests. I love tests. I am just a bit busy with the job, several own OSS projects, and also life.

The alternative fix, I think, would be removing this cpp check for // in the first line. C#, F# also have some comments. I played safe, just increased weight for F# specific files.

**Comment by techtonik** [comment]
`Go` uses // as well, so sound like a good choice.

**Pull request merged**
